server.port: 8080
spring.application.name: template-kotlin-springboot-webflux-r2dbc

server.error:
  include-message: always
  include-binding-errors: always
  include-exception: false
  include-stacktrace: always

# api
rest-api.cors:
  allowed-origin-patterns: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization, Content-Type"
  allow-credentials: true
  max-age: 3600

# api docs
springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    enabled: true
    path: /docs/api-v${springdoc.api-docs.api-version}
    api-version: 0.0.1

# database
spring.r2dbc:
  url: r2dbc:postgresql://127.0.0.1:5432/test-db
  username: postgres
  password: 1
  pool:
    enabled: true
    initial-size: 10
    max-size: 20


# logging configuration
spring.output.ansi.enabled: detect
logging:
  file.name: logs/app.log
  level:
    root: info
    org.springframework.web: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30